### PR TITLE
Bootstrap

### PR DESCRIPTION
**Pull request by sahilsimform**
@npsimform  I have added Bootstrap to the project.

### CODE REVIEW

**Comment by sahilsimform** [comment]
Add spacing in the main navbar   (done)
On hover its size get increased - it should work properly (partially done)
remove border from cards and add box-shadow (done)
all item images must have same height and spacing between them (done)

**Comment by sahilsimform** [comment]
@npsimform  I have updated the code. 
please review it.

**Review by npsimform — CHANGES_REQUESTED** [review]
- Header alignment is not proper on hover.

**Comment by sahilsimform** [comment]
@npsimform I have Updated the code.
Navbar Issue is resolved.

**Pull request merged**
